idf_component_register(
    SRCS
        "main.c"
        "led.c"
        "mcp251xfd.c"
        "can_manager.c"
        "can_filter.c"
        "controls/vehicle_control.c"
        "controls/battery_preheat.c"
        "automation/wiper_off.c"
        "automation/multi_finger.c"
        "can_sim.c"
        "ble_server.c"
        "ble_ota.c"
    INCLUDE_DIRS
        "."
        "controls"
        "automation"
        "debug"
    REQUIRES
        driver
        esp_adc
        nvs_flash
        bt
        esp_timer
        app_update
)
