// AUTO-GENERATED by tools/gen_dbc.py -- DO NOT EDIT.
// source: bus_1_tesla_vehicle.dbc + dbc/used_messages.txt
// Committed so a clean (Python-less) checkout still builds.
#pragma once

#include <stdint.h>

typedef enum {
    DBC_CKSUM_NONE = 0,
    DBC_CKSUM_TESLA_BYTESUM = 1,
} dbc_checksum_algo_t;

typedef struct {
    const char *name;
    uint16_t start_bit;   // LSB position (little-endian / Intel)
    uint8_t  length;      // signal width in bits
    uint8_t  is_signed;   // 1 = two's complement
    double   scale;       // phys = raw * scale + offset
    double   offset;
    int16_t  mux_sel_sig; // g_dbc_signals index of selector, or -1
    int32_t  mux_val;     // selector value enabling this signal, or -1
} dbc_signal_t;

typedef struct {
    const char *name;
    uint32_t id;
    uint8_t  dlc;
    uint8_t  default_bus;
    uint16_t sig_first;   // index of first signal in g_dbc_signals
    uint16_t sig_count;
    uint8_t  checksum_algo;
    int16_t  checksum_sig; // g_dbc_signals index, or -1
    int16_t  counter_sig;  // g_dbc_signals index, or -1
} dbc_message_t;

#define DBC_MESSAGE_COUNT 9
#define DBC_SIGNAL_COUNT  177

extern const dbc_message_t g_dbc_messages[DBC_MESSAGE_COUNT];
extern const dbc_signal_t  g_dbc_signals[DBC_SIGNAL_COUNT];

// Per-bus hardware RX acceptance-filter ID lists (11-bit standard
// IDs). Index g_dbc_hw_filters[] by physical bus id (0=chassis,
// 1=vehicle); program one exact-match MCP251xFD filter per id.
typedef struct {
    const uint16_t *ids;
    uint8_t         count;
} dbc_hw_filter_set_t;

#define DBC_HW_FILTER_BUS_COUNT 2
extern const dbc_hw_filter_set_t g_dbc_hw_filters[DBC_HW_FILTER_BUS_COUNT];
